In [2]:
import numpy as np
import scipy.linalg as la

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [4]:
a.shape

(6,)

In [5]:
type(a)

numpy.ndarray

In [6]:
a.dot(a.transpose())

np.int64(91)

In [7]:
a = np.array([[1], [2], [3], [4], [5], [6]])
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape = (6,1)

In [9]:
b = a.transpose()
print(b)

[[1 2 3 4 5 6]]


In [10]:
print("A=", a, "B=", b)

A= [[1]
 [2]
 [3]
 [4]
 [5]
 [6]] B= [[1 2 3 4 5 6]]


In [11]:
a.dot(b)

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [12]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])
print(a + b)
print(a-b)
print(2*a)

[3 6 9]
[-1 -2 -3]
[2 4 6]


In [13]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
a = np.ones((3, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
c = np.full((3,3), 1.1)
print(c)

[[1.1 1.1 1.1]
 [1.1 1.1 1.1]
 [1.1 1.1 1.1]]


In [16]:
d = np.random.random((3,3))
print(d)

[[0.90803679 0.21805934 0.28448839]
 [0.69093673 0.10093416 0.36857423]
 [0.48981209 0.1064512  0.19230996]]


In [17]:
a = np.array([1, 2, 3, 4, -5])
print(a)

[ 1  2  3  4 -5]


In [18]:
np.linalg.norm(a, ord=1)

np.float64(15.0)

In [19]:
np.linalg.norm(a)

np.float64(7.416198487095663)

In [20]:
np.linalg.norm(a, ord=2)

np.float64(7.416198487095663)

In [21]:
b = np.array([2, 2])
np.linalg.norm(b)

np.float64(2.8284271247461903)

In [22]:
np.sqrt(2**2 + 2**2)

np.float64(2.8284271247461903)

In [23]:
np.linalg.norm(a, ord=np.inf)

np.float64(5.0)

In [24]:
b = np.array([3, 4, -23, -14])
np.linalg.norm(b, ord=np.inf)

np.float64(23.0)

In [25]:
from scipy.spatial import distance

In [26]:
distance.chebyshev([100, 90], [89, 30])

np.int64(60)

In [31]:
distance.euclidean([1, 3], [3, 4])

np.float64(2.23606797749979)

In [30]:
np.sqrt(5)

np.float64(2.23606797749979)

In [37]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[11, 12], [13, 14], [15, 16]])
print("A=", A,"\n" "B=", B)

A= [[1 2]
 [3 4]
 [5 6]] 
B= [[11 12]
 [13 14]
 [15 16]]


In [38]:
2 * A

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [42]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
A + 2

array([[3, 4],
       [5, 6],
       [7, 8]])

In [46]:
A.shape

(3, 2)

In [50]:
np.random.random(A.shape)

array([[0.30337328, 0.73441506],
       [0.96708788, 0.31136063],
       [0.74956456, 0.40468381]])

In [57]:
print(A, "\n", B)

[[1 2]
 [3 4]
 [5 6]] 
 [[11 12]
 [13 14]
 [15 16]]


In [55]:
A / B

array([[0.09090909, 0.16666667],
       [0.23076923, 0.28571429],
       [0.33333333, 0.375     ]])

In [58]:
6/16

0.375

In [59]:
A * B

array([[11, 24],
       [39, 56],
       [75, 96]])

In [73]:
a = np.array([[1, 2], [4, 5]])
b = np.array([[11, 12], [13, 14]])

In [74]:
print(a)
print(b)

[[1 2]
 [4 5]]
[[11 12]
 [13 14]]


In [75]:
a.dot(b)

array([[ 37,  40],
       [109, 118]])

In [76]:
a * b

array([[11, 24],
       [52, 70]])

In [77]:
a @ b

array([[ 37,  40],
       [109, 118]])

In [78]:
a

array([[1, 2],
       [4, 5]])

In [82]:
1/11

0.09090909090909091

In [83]:
a

array([[1, 2],
       [4, 5]])

In [84]:
a.dot(3)

array([[ 3,  6],
       [12, 15]])

In [92]:
A = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2]])

In [93]:
A

array([[1, 2],
       [3, 4]])

In [94]:
b

array([[1, 2]])

In [95]:
b.shape

(1, 2)

In [132]:
# Cosine similarity

a = np.array([1,2])
b = np.array([3,4])
np.dot(a, b) / [np.linalg.norm(a) * np.linalg.norm(b)]

array([0.98386991])

In [129]:
11/(11.180339887498949)

0.9838699100999074

In [118]:
np.linalg.norm(a)

np.float64(2.23606797749979)

In [102]:
np.linalg.norm(a) * np.linalg.norm(b)

np.float64(10.000000000000002)

In [109]:
np.linalg.norm(a) * np.linalg.norm(b)

np.float64(10.000000000000002)

In [110]:
(np.linalg.norm(a) * np.linalg.norm(b))

np.float64(10.000000000000002)

In [111]:
[np.linalg.norm(a) * np.linalg.norm(b)]

[np.float64(10.000000000000002)]

In [133]:
u = np.array([6, 7])
v = np.array([5, -12])

In [141]:
# Projection of u on v
(np.dot(u, v) / (np.linalg.norm(v)**2)) * v

array([-1.59763314,  3.83431953])

In [ ]:
(-54/(np.sqrt(5**2 + (-12)**2))*2)

np.float64(-4.153846153846154)

In [145]:
u = np.array([1, 2, 3])
v = np.array([5, 6, 2])

In [146]:
(np.dot(u, v) / (np.linalg.norm(v)**2)) * v

array([1.76923077, 2.12307692, 0.70769231])

In [144]:
np.sqrt(1**2 + 2**2 + 3**2)

np.float64(3.7416573867739413)

In [151]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [152]:
u = np.array([1, 3, ])
v = np.array([2, 1])

In [153]:
a = 2
b = 1
a*u+b*v

array([4, 7])

In [156]:
u = np.array([[1], [0]])
v = np.array([[0], [1]])
w = np.array([[2], [1]])

In [160]:
lin_combination = 2*u + 1*v

In [161]:
lin_combination

array([[2],
       [1]])

In [162]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [163]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [164]:
M = np.random.random((3, 3))

In [165]:
M

array([[0.195646  , 0.33762213, 0.39231756],
       [0.07189433, 0.33132182, 0.58532731],
       [0.50336383, 0.85427591, 0.82474643]])

In [166]:
d = np.diag(M)

In [167]:
d

array([0.195646  , 0.33132182, 0.82474643])

In [168]:
D = np.diag(d)

In [169]:
D

array([[0.195646  , 0.        , 0.        ],
       [0.        , 0.33132182, 0.        ],
       [0.        , 0.        , 0.82474643]])

In [170]:
np.tril(np.random.random((3,3)))

array([[0.41760692, 0.        , 0.        ],
       [0.89113023, 0.6559705 , 0.        ],
       [0.47565992, 0.57293639, 0.91891089]])

In [171]:
np.triu(np.random.random((3,3)))

array([[0.20889995, 0.08399124, 0.92907368],
       [0.        , 0.77880914, 0.84988874],
       [0.        , 0.        , 0.67970738]])

In [172]:
M

array([[0.195646  , 0.33762213, 0.39231756],
       [0.07189433, 0.33132182, 0.58532731],
       [0.50336383, 0.85427591, 0.82474643]])

In [173]:
M.T

array([[0.195646  , 0.07189433, 0.50336383],
       [0.33762213, 0.33132182, 0.85427591],
       [0.39231756, 0.58532731, 0.82474643]])

In [176]:
M.dot(M.T)

array([[0.30617913, 0.3555616 , 0.71046608],
       [0.3555616 , 0.45755101, 0.80197586],
       [0.71046608, 0.80197586, 1.66336914]])

In [178]:
np.linalg.inv(M)

array([[ 36.30753007,  -9.0770679 , -10.82881413],
       [-37.6785771 ,   5.78298019,  13.81883051],
       [ 16.86821925,  -0.45006931,  -6.49200838]])