#Matrix transformations

1. For the given matrix scale by factor of 4 and rotate a matrix by 50 degree

In [4]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt

def get_grid(x, y, homogenous=False):
    coords = np.indices((x, y)).reshape(2, -1)
    return np.vstack((coords, np.ones(coords.shape[1]))).astype(np.int) if homogenous else coords

def grid_plotter(points, labels):
    markers = ['o', 'x', 's', '^', 'p', 'v']
    fig, ax = plt.subplots(figsize=(8,6))
    for i, p in enumerate(points):
        x, y = p[0], p[1]
        ax.scatter(x, y, label=labels[i], marker=markers[i], alpha=0.8, s=100)
    ax.legend(loc='lower right')
    ax.set_xlim(-5, 5)
    ax.set_ylim(-5, 5)

    ax.grid(True)
    plt.show()

In [5]:
# Define Transformations
def get_rotation(angle):
    angle = np.radians(angle)
    return np.array([
        [np.cos(angle), -np.sin(angle), 0],
        [np.sin(angle),  np.cos(angle), 0],
        [0, 0, 1]
    ])


def get_scale(s):
    return np.array([
        [s, 0, 0],
        [0, s, 0],
        [0, 0, 1]
    ])

R1 = get_rotation(50)
S1 = get_scale(2)

In [6]:

# Get sample coordinates
coords = get_grid(2, 2, homogenous=True)

# Apply transformation
coords_rot = R1 @ coords
coords_scale = S1 @ coords

coords_composite1 = R1 @ S1 @ coords

grid_plotter([coords, coords_rot, coords_scale, coords_composite1],
             labels=['original', 'rotate135', 'scale(2)', 'rotate(50), scale(4)'])

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#Matrix operations

2. For the given matrix A, find
- determinant
- rank
- inverse
- Eigen value

In [7]:
# matrix determinant
from numpy import array
from numpy.linalg import det
from numpy.linalg import matrix_rank

# define matrix
A = array([
[22, 32, 13],
[14, 5, 16],
[19, 18, 15]])

print(A)

[[22 32 13]
 [14  5 16]
 [19 18 15]]


In [8]:
det = det(A)
rank = matrix_rank(A)
inv= np.linalg.inv(A)
eigenvalues, eigenvectors = np.linalg.eig(A)

3. Convert the following matrix to an orthogonal matrix using Gram Schmidt Process.

In [9]:
A = np.array([[9,8,7], [6,5,4], [3,2,1]])
A

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

Check if the above matrix is orthogonal and if not, convert to an orthogonal matrix.

In [10]:
A.dot(A.T)

array([[194, 122,  50],
       [122,  77,  32],
       [ 50,  32,  14]])

since the inner/ dot product of A and A Transpose is not an identity matrix, the matrix A is not orthogonal.

In [11]:
# Gram Schmidt Process