In [2]:
import numpy as np
import scipy.linalg as la

### Creation of Vectors and Matrices

1. Create a row vector and a column vector of natural numbers of size 6.

### Row Vector

In [3]:
row_vec = np.array([1, 2, 3, 4, 5, 6])
row_vec

array([1, 2, 3, 4, 5, 6])

The shape and type of the vectors can be checked using array_name.shape and type(array_name)

In [4]:
row_vec.shape

(6,)

### Column Vector

In [9]:
col_vec = np.array([[1],  [2], [3], [4], [5], [6]])
col_vec

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

2. Create a 3 x 3 matrix of all zeros, all ones, all with a value of 5 and all with random values.

In [11]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
fives = np.full((3, 3), 5)
fives

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [15]:
rands = np.random.rand(3,3)
rands

array([[0.60613518, 0.09200856, 0.1821615 ],
       [0.34335044, 0.01298384, 0.95254589],
       [0.13850555, 0.3555496 , 0.2126969 ]])

In [16]:
rands_nums = np.random.randint(10, 20, size=(3, 3))
rands_nums

array([[16, 18, 17],
       [14, 16, 19],
       [17, 16, 10]])

3. a. Create a 3 x 2 matrix using an array of lists and print the type of the array.

   b. Create a 2 x 5 matrix using an array of lists and print the type of the array.

In [21]:
mat32 = [[1, 2], [3, 4], [5, 6]]
print(mat32)
type(mat32)
arr_np = np.array(mat32)
print(arr_np)
type(arr_np)
arr_np.shape

[[1, 2], [3, 4], [5, 6]]
[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [22]:
# b
mat25 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]
mat25 = np.array(mat25)
mat25.shape

(2, 5)

# Vector and Matrix Operations 


4. Find the magnitude/ L1 and L2 norm of the vector [2,3] and state which has has a highest value.


In [23]:
v = np.array([2, 3])
print(np.linalg.norm(v))
print("Manhattan L1", np.linalg.norm(v, ord=1))
print("Euclidean L2", np.linalg.norm(v, ord=2))

3.605551275463989
Manhattan L1 5.0
Euclidean L2 3.605551275463989


## Vector and Matrix Arithmetic 

5. Perform addition, subtraction, multiplication and division of two matrices of size (3 x 3)

In [24]:
A = np.random.randint(1, 5, size=(3, 3))
B = np.random.randint(5, 9, size=(3, 3))
print(A)
print(B)

[[2 2 1]
 [3 2 2]
 [4 1 2]]
[[5 7 7]
 [7 7 7]
 [8 7 8]]


In [25]:
A + B

array([[ 7,  9,  8],
       [10,  9,  9],
       [12,  8, 10]])

In [26]:
A - B

array([[-3, -5, -6],
       [-4, -5, -5],
       [-4, -6, -6]])

In [29]:
A / B

array([[0.4       , 0.28571429, 0.14285714],
       [0.42857143, 0.28571429, 0.28571429],
       [0.5       , 0.14285714, 0.25      ]])

In [27]:
A * B

array([[10, 14,  7],
       [21, 14, 14],
       [32,  7, 16]])

In [28]:
np.dot(A, B)

array([[32, 35, 36],
       [45, 49, 51],
       [43, 49, 51]])

In [30]:
A.dot(B)

array([[32, 35, 36],
       [45, 49, 51],
       [43, 49, 51]])

In [34]:
np.matmul(A, B)

array([[32, 35, 36],
       [45, 49, 51],
       [43, 49, 51]])

## Dot product

6. Find the dot product of the matrices created above.

In [35]:
np.dot(A, B)

array([[32, 35, 36],
       [45, 49, 51],
       [43, 49, 51]])

### Scalar and Vector Projections
7. Find the scalar and vector projections of the vector  u = 8i + 6j on vector v = i - 7j


In [37]:
u = np.array([8, 6])
v = np.array([1, -7])

In [38]:
# scalar
np.dot(u, v) / np.linalg.norm(v)

np.float64(-4.808326112068523)

In [50]:
scal = np.dot(v, u) / np.linalg.norm(v)
scal

np.float64(-4.808326112068523)

In [52]:
(scal * v) / np.linalg.norm(v)

array([-0.68,  4.76])

#### Transpose of a matrix

8. Create the transpose of the 3*3 matrix created above. 

In [40]:
np.transpose(A)

array([[2, 3, 4],
       [2, 2, 1],
       [1, 2, 2]])

In [41]:
A.T

array([[2, 3, 4],
       [2, 2, 1],
       [1, 2, 2]])

The matrix changes shape such that the rows become columns and columns become rows.

### Identity Matrix

9. Create a 3*3 identity matrix.

In [42]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Types of Matrices

10. Create a square matrix of size 3x3 and print 
a. upper triangular matrix
b. lower triangular matrix
c. diagonal matrix



In [45]:
squ_mat = np.random.randint(10, 20, size=(3, 3))
squ_mat

array([[13, 16, 19],
       [10, 16, 17],
       [15, 11, 14]])

In [47]:
np.tril(squ_mat)

array([[13,  0,  0],
       [10, 16,  0],
       [15, 11, 14]])

In [48]:
np.triu(squ_mat)

array([[13, 16, 19],
       [ 0, 16, 17],
       [ 0,  0, 14]])

In [49]:
np.diag(squ_mat)

array([13, 16, 14])